version: "3"
services: 
  frontend:
    image: syjjem093/birfrontend:3
    restart: always
    depends_on:
      - backend
    ports: 
      - 56:3000 
  backend:
    image: syjjem093/birbackend:3
    restart: always
    depends_on:
      - mongodb
    ports:
      - 73:4343
  mongodb: 
     image: mongo
     restart: always
     ports:
      - 27017:27017
     environment:
       MONGO_INITDB_ROOT_USERNAME: sijuade
       MONGO_INITDB_ROOT_PASSWORD: 80ZGPwOkxOZUqmAo
       MONGO_INITDB_DATABASE: books_i_read          
